### PR TITLE
re-build documentation as part of Docker build [#6]

### PR DESCRIPTION
**Pull request by lkeegan**
As part of the Docker build process, re-generate the .ipynb
    example notebooks using the newly built version of STEPS
    inside the image. [#6]

    NB: Removed blas, mpi and lapack locations from petsc build
    as the libraries were not in specified locations, causing
    a build error in petsc. Also added -O3 compiler flag
    instead of the implied default -O0 for petsc.

    Added libsbml to image to be able to run sbml_importer.ipynb

    Note: currently use a hard coded list of filenames
    to exclude the following files which give errors when ran:
    - matlab_support: image doesn't contain matlab
    - memb_pot: SyntaxError (I think due to a future statement not at top of file)

### CODE REVIEW

**Comment by tristan0x** [comment]
Thanks @lkeegan for the petsc build improvement!
Can you try to fix `memb_pot` while you are at it?

I am currently building the Docker image on my workstation to see how it goes.

**Comment by tristan0x** [comment]
> Can you try to fix `memb_pot` while you are at it?

I am stupid, this is in another repository. Can you please open an issue in `STEPS_Example` repository?

**Comment by tristan0x** [comment]
> > Can you try to fix `memb_pot` while you are at it?
> 
> I am stupid, this is in another repository. Can you please open an issue in `STEPS_Example` repository?

This issue has just been fixed by CNS-OIST/STEPS_Example#11
Can you please update Dockerfile to rebuild this notebook as well?

**Comment by lkeegan** [comment]
> > > Can you try to fix `memb_pot` while you are at it?
> > 
> > 
> > I am stupid, this is in another repository. Can you please open an issue in `STEPS_Example` repository?
> 
> This issue has just been fixed by [CNS-OIST/STEPS_Example#11](https://github.com/CNS-OIST/STEPS_Example/pull/11)
> Can you please update Dockerfile to rebuild this notebook as well?
done & squashed to a single commit

**Comment by lkeegan** [comment]
with an increased timeout for nbconvert the image now builds successfully for me

**Review by tristan0x — APPROVED** [review]

**Pull request merged**
